<?php
# This file was automatically generated by the MediaWiki 1.31.8
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";
$wgScriptExtension = ".php";
$wgArticlePath = "/$1";
$wgVariantArticlePath = "/$2/$1";
$wgUsePathInfo = true;
$wgDefaultLanguageVariant = "zh-cn";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "主站域名";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;



# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$wgResourceBasePath/resources/assets/wiki.png";
## 网站图标
$wgFavicon = "$wgResourceBasePath/resources/assets/favicon.ico";

## Apple电子设备图标
$wgAppleTouchIcon = "$wgResourceBasePath/resources/assets/apple-touch-icon.png";
## UPO means: this is also a user preference option

## Database settings
$wgDBtype = "";
$wgDBserver = "";
$wgDBname = "";
$wgDBuser = "";
$wgDBpassword = "";

$wgEnableUploads  = false;

wfLoadSkin( 'MinervaNeue' );

require_once( "$IP/CommonSettings.php" );
require_once( "$IP/SessionCache.php" );

wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'MobileFrontend' );
wfLoadExtension( 'MultiBoilerplate' );
wfLoadExtension( 'OATHAuth' );
wfLoadExtension( 'RelatedArticles' );

$wgUploadNavigationUrl = "https://共享站域名/index.php/Special:Upload";
$wgUseSharedUploads = true;
$wgSharedUploadPath = 'https://共享站域名/images';
$wgSharedUploadDirectory = '上传文件存放位置';
$wgHashedSharedUploadDirectory = true;

$wgFetchCommonsDescriptions = true;
$wgSharedUploadDBname = '共享站数据库';  # DB-Name of PoolWiki
$wgRepositoryBaseUrl = "https://共享站域名/File:";


$wgForeignFileRepos[] = [
	'class' => 'ForeignDBViaLBRepo',
	'wiki' => '共享站数据库',
	'name' => 'wikifile', # displayname (eg. the vector-skin-tab “View on OtherWiki“) may be set at wiki-specific MediaWiki:Shared-repo-name-<otherwiki>
	'url' => 'https://共享站域名/images',
	'directory' => '上传文件存放位置',
	'hashLevels' => 2, # This must be the same for the other family member
	'hasSharedCache' => false,
	'fetchDescription' => true,
	'scriptDirUrl' => 'https://共享站域名/', # has effect whether description can be fetched
];

$wgGenerateThumbnailOnParse = true;