<?php
# This file was automatically generated by the MediaWiki 1.31.8
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";
$wgScriptExtension = ".php";
$wgArticlePath = "/$1";
$wgUsePathInfo = true;;

## The protocol and server name to use in fully-qualified URLs
$wgServer = "共享站域名";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;


# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$wgResourceBasePath/resources/assets/wiki.png";
## 网站图标
$wgFavicon = "$wgResourceBasePath/resources/assets/favicon.ico";

## Apple电子设备图标
$wgAppleTouchIcon = "$wgResourceBasePath/resources/assets/apple-touch-icon.png";
## UPO means: this is also a user preference option

$wgDBtype = "";
$wgDBserver = "";
$wgDBname = "";
$wgDBuser = "";
$wgDBpassword = "";

$wgEnableUploads  = true;
$wgGenerateThumbnailOnParse = true;

require_once( "$IP/CommonSettings.php" );
require_once( "$IP/SessionCache.php" );

require_once( "$IP/extensions/MoeUpload/MoeUpload.php" );


$wgSharedDB = '主站数据库名'; # The $wgDBname for the wiki database holding the main user table
$wgSharedTables = [ 'user', 'user_properties' ];
$wgSharedTables[] = 'user_groups';
$wgSharedTables[] = 'ipblocks';
$wgSharedTables[] = 'abuse_filter';
$wgSharedTables[] = 'abuse_filter_action';
$wgSharedTables[] = 'abuse_filter_history';
$wgSharedTables[] = 'abuse_filter_log';
$wgSharedTables[] = 'globalblocks';
$wgSharedTables[] = 'global_block_whitelist';
$wgSharedTables[] = 'interwiki';

